spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      dicovery: GATEWAY
  application:
    name: GATEWAY
cloud:
  gateway:
    globalcors:
      corsConfigurations:
      '[/**]':
      allowedOrigins: "*"
      allowedMethods: "*"
      allowedHeaders: "*"

server:
  port: 8888
